### PR TITLE
Refactor workflow to calculate powder pattern by PyRS routine

### PR DESCRIPTION
**Pull request by wdzhou**
Try to reduce the number of matrix rotation operation.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
@quantumsteve was about to start in on this in #290.

**Comment by wdzhou** [comment]
*Improvement*

Before

After
`
[INFO] Sub run splitting duration = 14.351761 second from 2020-01-21 15:57:28.016016 to 
[INFO] Sub run splitting duration = 170.448583 second from 2020-01-21 15:57:42.367777 to 
real	    12m37.847s
user	7m6.749s
`

**Comment by wdzhou** [comment]
**Improve on Run 1060**

After
```
[INFO] Sub run splitting duration = 1.037887 second from 2020-01-21 15:29:57.664160 to 2020-01-21 15:29:58.702047
[INFO] Sub run splitting duration = 0.721119 second from 2020-01-21 15:29:58.702047 to 2020-01-21 15:29:59.423166

real	0m55.078s
user	0m49.654s
sys	0m20.217s

```

**Comment by wdzhou** [comment]
The speedup achieved in this PR is simply by rearranging the operations to calculate each pixel's position and thus 2theta.  Neither multiple threading nor new workflow to take advantage of unchanged 2theta values is implemented here.  Thus further speedup could be expected.

@quantumsteve : The change could be contributed to #290.  Or at least it could be a good reference.  I won't merge it until discussing with you.

**Pull request merged**
