### PR TITLE
Remove old test using simulated data

### PR DESCRIPTION
**Pull request by quantumsteve**
Remove `tests/unit/test_reduction.py` that is from before real data from HIDRA was available.

Test data appears to be used elsewhere and therefore not removed in this PR.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@peterfpeterson How do you want to handle https://github.com/neutrons/PyRS/blob/6888c5b15807bc540009bae7a5a8c82544074c43/pyrs_calibration.sh#L50 and https://github.com/neutrons/PyRS/blob/6888c5b15807bc540009bae7a5a8c82544074c43/pyrs_calibration.sh#L51 ?

**Comment by peterfpeterson** [comment]
@wdzhou Can `pyrs_calibration.sh` be removed from the repository too? I'm suspicious that several of the wrapper scripts can go away.

**Comment by wdzhou** [comment]
@peterfpeterson Definitely!  It was a prototype.

**Comment by wdzhou** [comment]
Here are the .sh that can be removed.  
 - create_calibration_masks.sh
 - pyrs_command.sh
 - pyrs_generatemasks.sh
 - pyrs_gui_test.sh
 - pyrs_project_format_test.sh
 - pyrs_widgets_test.sh

**Comment by quantumsteve** [comment]
I removed `pyrs_calibration.sh` and the other shell scripts @wdzhou has above.

**Pull request merged**
